[package]
name = "phlow-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
phlow = { path = "../phlow" }
phlow-extensions = { path = "../phlow-extensions" }
value-box = "1.1"
string-box = "1.1"
env_logger = "0.8"

[lib]
name = "Phlow"
crate-type = ["cdylib"]